import type { User, Project, Application, Thread, Comment, Notification, Conversation, Message } from '../types/api';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ana García',
    email: 'ana@example.com',
    role: 'developer',
    status: 'active',
    stack: ['React', 'TypeScript', 'Node.js'],
    bio: 'Full-stack developer con pasión por la UI/UX',
    createdAt: '2026-01-15T10:00:00Z',
    projectsCount: 3,
    collaborationsCount: 5,
  },
  {
    id: '2',
    name: 'Carlos Mendoza',
    email: 'carlos@example.com',
    role: 'developer',
    status: 'active',
    stack: ['Python', 'Django', 'PostgreSQL'],
    bio: 'Backend specialist, data enthusiast',
    createdAt: '2026-02-01T10:00:00Z',
    projectsCount: 2,
    collaborationsCount: 3,
  },
  {
    id: '3',
    name: 'María Rodriguez',
    email: 'maria@example.com',
    role: 'moderator',
    status: 'active',
    stack: ['Vue.js', 'Java', 'Spring Boot'],
    bio: 'Tech lead & community moderator',
    createdAt: '2025-11-10T10:00:00Z',
    projectsCount: 5,
    collaborationsCount: 8,
  },
  {
    id: '4',
    name: 'Luis Torres',
    email: 'luis@example.com',
    role: 'admin',
    status: 'active',
    stack: ['React', 'Python', 'AWS'],
    bio: 'Platform administrator',
    createdAt: '2025-10-01T10:00:00Z',
    projectsCount: 1,
    collaborationsCount: 2,
  },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Social Analytics Dashboard',
    description: 'Plataforma de análisis de redes sociales en tiempo real con visualizaciones interactivas',
    stackRequired: ['React', 'TypeScript', 'Python', 'FastAPI'],
    status: 'seeking_collaborators',
    creatorId: '1',
    creator: mockUsers[0],
    collaborators: [],
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-04-10T10:00:00Z',
    applicationCount: 3,
  },
  {
    id: '2',
    title: 'E-commerce Marketplace',
    description: 'Marketplace multi-vendor con sistema de pagos integrado y gestión de inventario',
    stackRequired: ['Vue.js', 'Node.js', 'MongoDB', 'Stripe'],
    status: 'in_development',
    creatorId: '2',
    creator: mockUsers[1],
    collaborators: [mockUsers[0], mockUsers[2]],
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-04-15T10:00:00Z',
    startedAt: '2026-04-01T10:00:00Z',
    applicationCount: 0,
  },
  {
    id: '3',
    title: 'Task Management App',
    description: 'Aplicación de gestión de tareas con funcionalidades de colaboración en equipo',
    stackRequired: ['React', 'Django', 'PostgreSQL'],
    status: 'seeking_collaborators',
    creatorId: '3',
    creator: mockUsers[2],
    collaborators: [],
    createdAt: '2026-04-12T10:00:00Z',
    updatedAt: '2026-04-12T10:00:00Z',
    applicationCount: 5,
  },
  {
    id: '4',
    title: 'Real-time Chat Platform',
    description: 'Sistema de mensajería instantánea con canales, hilos y videollamadas',
    stackRequired: ['React', 'Node.js', 'WebRTC', 'Socket.io'],
    status: 'completed',
    creatorId: '1',
    creator: mockUsers[0],
    collaborators: [mockUsers[1]],
    createdAt: '2026-01-05T10:00:00Z',
    updatedAt: '2026-03-30T10:00:00Z',
    startedAt: '2026-01-20T10:00:00Z',
    completedAt: '2026-03-30T10:00:00Z',
    applicationCount: 0,
  },
  {
    id: '5',
    title: 'AI Code Assistant',
    description: 'Asistente de código basado en IA para autocompletado y refactorización',
    stackRequired: ['Python', 'TensorFlow', 'FastAPI', 'React'],
    status: 'draft',
    creatorId: '2',
    creator: mockUsers[1],
    collaborators: [],
    createdAt: '2026-04-16T10:00:00Z',
    updatedAt: '2026-04-16T10:00:00Z',
    applicationCount: 0,
  },
];

// Mock Applications
export const mockApplications: Application[] = [
  {
    id: '1',
    projectId: '1',
    project: mockProjects[0],
    applicantId: '2',
    applicant: mockUsers[1],
    message: 'Me interesa colaborar en el backend con Python y FastAPI. Tengo experiencia en APIs RESTful.',
    status: 'pending',
    createdAt: '2026-04-11T10:00:00Z',
    updatedAt: '2026-04-11T10:00:00Z',
  },
  {
    id: '2',
    projectId: '1',
    project: mockProjects[0],
    applicantId: '3',
    applicant: mockUsers[2],
    message: 'Puedo ayudar con la arquitectura frontend y las visualizaciones.',
    status: 'pending',
    createdAt: '2026-04-12T10:00:00Z',
    updatedAt: '2026-04-12T10:00:00Z',
  },
  {
    id: '3',
    projectId: '3',
    project: mockProjects[2],
    applicantId: '1',
    applicant: mockUsers[0],
    message: 'Excelente proyecto! Me gustaría trabajar en el frontend con React.',
    status: 'accepted',
    createdAt: '2026-04-13T10:00:00Z',
    updatedAt: '2026-04-14T10:00:00Z',
  },
];

// Mock Threads
export const mockThreads: Thread[] = [
  {
    id: '1',
    projectId: '2',
    authorId: '1',
    author: mockUsers[0],
    title: '¿Qué estrategia de caché implementamos?',
    content: 'Necesitamos decidir entre Redis y Memcached para el caché de sesiones y datos frecuentes.',
    category: 'architecture',
    createdAt: '2026-04-02T10:00:00Z',
    updatedAt: '2026-04-03T10:00:00Z',
    commentsCount: 3,
  },
  {
    id: '2',
    projectId: '2',
    authorId: '2',
    author: mockUsers[1],
    title: 'Bug en el proceso de checkout',
    content: 'Cuando el usuario tiene múltiples direcciones, el checkout falla al validar.',
    category: 'bug',
    createdAt: '2026-04-05T10:00:00Z',
    updatedAt: '2026-04-05T10:00:00Z',
    commentsCount: 1,
  },
];

// Mock Comments
export const mockComments: Comment[] = [
  {
    id: '1',
    threadId: '1',
    authorId: '2',
    author: mockUsers[1],
    content: 'Yo votaría por Redis. Tiene mejor soporte para estructuras de datos complejas.',
    createdAt: '2026-04-02T11:00:00Z',
  },
  {
    id: '2',
    threadId: '1',
    authorId: '3',
    author: mockUsers[2],
    content: 'De acuerdo con Redis. Además, podemos usar Redis Pub/Sub para notificaciones en tiempo real.',
    createdAt: '2026-04-02T14:00:00Z',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'application_received',
    title: 'Nueva postulación',
    message: 'Carlos Mendoza se postuló a tu proyecto "Social Analytics Dashboard"',
    read: false,
    link: '/project/1',
    createdAt: '2026-04-11T10:00:00Z',
  },
  {
    id: '2',
    userId: '1',
    type: 'new_comment',
    title: 'Nuevo comentario',
    message: 'María Rodriguez comentó en el debate "¿Qué estrategia de caché implementamos?"',
    read: true,
    link: '/project/2/threads/1',
    createdAt: '2026-04-02T14:00:00Z',
  },
];

// Mock Messages & Conversations
export const mockMessages: Message[] = [
  {
    id: '1',
    conversationId: 'conv-1-2',
    senderId: '2',
    sender: mockUsers[1],
    receiverId: '1',
    receiver: mockUsers[0],
    content: 'Hola Ana, me interesa mucho tu proyecto de analytics. ¿Podemos hablar sobre la arquitectura?',
    read: true,
    createdAt: '2026-04-11T11:00:00Z',
  },
  {
    id: '2',
    conversationId: 'conv-1-2',
    senderId: '1',
    sender: mockUsers[0],
    receiverId: '2',
    receiver: mockUsers[1],
    content: 'Claro! Estaba pensando en una arquitectura de microservicios con eventos.',
    read: true,
    createdAt: '2026-04-11T11:30:00Z',
  },
  {
    id: '3',
    conversationId: 'conv-1-3',
    senderId: '3',
    sender: mockUsers[2],
    receiverId: '1',
    receiver: mockUsers[0],
    content: 'Hey! Vi que aceptaste mi postulación. Cuándo empezamos?',
    read: false,
    createdAt: '2026-04-14T10:00:00Z',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1-2',
    participantIds: ['1', '2'],
    participants: [mockUsers[0], mockUsers[1]],
    lastMessage: mockMessages[1],
    unreadCount: 0,
    updatedAt: '2026-04-11T11:30:00Z',
  },
  {
    id: 'conv-1-3',
    participantIds: ['1', '3'],
    participants: [mockUsers[0], mockUsers[2]],
    lastMessage: mockMessages[2],
    unreadCount: 1,
    updatedAt: '2026-04-14T10:00:00Z',
  },
];
